services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wijekoon-frontend:latest
    container_name: wijekoon-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:80"
